/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "globals.h"
#include "GUI.h"
#include "WM.h"
#include "Test_StateMachine.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0    (GUI_ID_USER + 0x00) //GuideMainWindow
#define ID_BUTTON_0    (GUI_ID_USER + 0x01) //GuideMain
#define ID_BUTTON_1    (GUI_ID_USER + 0x02) //AlarmShow
#define ID_TEXT_0    (GUI_ID_USER + 0x03) //PageName
#define ID_BUTTON_4    (GUI_ID_USER + 0x04) //Skip
#define ID_BUTTON_5    (GUI_ID_USER + 0x05) //PreviousStep
#define ID_BUTTON_6    (GUI_ID_USER + 0x06) //NextStep
#define ID_BUTTON_7		 (GUI_ID_USER + 0x07) //Finish


// USER START (Optionally insert additional defines)

// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
FocusableListItem fliSkip;
FocusableListItem fliPrevious;
FocusableListItem fliNext;
FocusableListItem fliFinish;
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "GuideMainWindow", ID_WINDOW_0, 0, 0, 800, 480, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "GuideMain", ID_TEXT_0, 50, 30, 200, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Skip", ID_BUTTON_4, 344, 400, 80, 45, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "PreviousStep", ID_BUTTON_5, 452, 400, 80, 45, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "NextStep", ID_BUTTON_6, 560, 400, 80, 45, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Finish", ID_BUTTON_7, 668, 400, 80, 45, 0, 0x0, 0 },
  
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;

  // USER START (Optionally insert additional variables)
  WM_KEY_INFO *key_info;
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'GuideMainWindow'
    //
    hItem = pMsg->hWin;
    // USER START (Optionally insert additional code for further widget initialization)
	TEXT_SetFont(WM_GetDialogItem(pMsg->hWin, ID_TEXT_0), GUI_FONT_COMIC24B_1);
	WINDOW_SetBkColor(hItem, GUI_WHITE);

	BUTTON_SetFocussable(WM_GetDialogItem(hItem, ID_BUTTON_4), 1);
	BUTTON_SetFocussable(WM_GetDialogItem(hItem, ID_BUTTON_5), 1);
	BUTTON_SetFocussable(WM_GetDialogItem(hItem, ID_BUTTON_6), 1);

	WM_DisableWindow(WM_GetDialogItem(hItem, ID_BUTTON_7));
	BUTTON_SetFocussable(WM_GetDialogItem(hItem, ID_BUTTON_7), 0);

	WM_SetFocus(WM_GetDialogItem(hItem, ID_BUTTON_6));

    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
	hItem = pMsg->hWin;
    NCode = pMsg->Data.v;
    switch(Id) {
	case ID_BUTTON_4: // Notifications sent by 'Skip'
		switch (NCode) {
		case WM_NOTIFICATION_CLICKED:
			// USER START (Optionally insert code for reacting on notification message)
			// USER END
			break;
		case WM_NOTIFICATION_RELEASED:
			// USER START (Optionally insert code for reacting on notification message)
			GSM_SwitchState(DataShowWindow);
			// USER END
			break;
			// USER START (Optionally insert additional code for further notification handling)
			// USER END
		}
		break;
	case ID_BUTTON_5: // Notifications sent by 'PreviousStep'
		switch (NCode) {
		case WM_NOTIFICATION_CLICKED:
			// USER START (Optionally insert code for reacting on notification message)
			// USER END
			break;
		case WM_NOTIFICATION_RELEASED:
			// USER START (Optionally insert code for reacting on notification message)
			GSM_PreviousState();
			// USER END
			break;
			// USER START (Optionally insert additional code for further notification handling)
			// USER END
		}
		break;
	case ID_BUTTON_6: // Notifications sent by 'NextStep'
		switch (NCode) {
		case WM_NOTIFICATION_CLICKED:
			// USER START (Optionally insert code for reacting on notification message)
			// USER END
			break;
		case WM_NOTIFICATION_RELEASED:
			// USER START (Optionally insert code for reacting on notification message)
			GSM_NextState();
			// USER END
			break;
			// USER START (Optionally insert additional code for further notification handling)
			// USER END
		}
		break;
	case ID_BUTTON_7: // Notifications sent by 'Finish'
		switch (NCode) {
		case WM_NOTIFICATION_CLICKED:
			// USER START (Optionally insert code for reacting on notification message)
			// USER END
			break;
		case WM_NOTIFICATION_RELEASED:
			// USER START (Optionally insert code for reacting on notification message)	
			GSM_SwitchState(DataShowWindow);
			// USER END
			break;
			// USER START (Optionally insert additional code for further notification handling)
			// USER END
		}
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  case WM_KEY:
	  hItem = pMsg->hWin;
	  key_info = (WM_KEY_INFO*)pMsg->Data.p;
	  if (SM_KeyProc(key_info, hItem)) {
		  // Do nothing
	  }
	  else {
		  WM_DefaultProc(pMsg);
	  }
	  break;
  case WM_GUIDE_STATE_ENTER:
	  hItem = pMsg->hWin;
	  if (GSM_GetCurrentState() == GStep7Window)
	  {
		  GSM_EnableButton(WM_GetDialogItem(hItem, ID_BUTTON_7));
		  GSM_DisableButton(WM_GetDialogItem(hItem, ID_BUTTON_4));
	  }
	  else {
		  GSM_EnableButton(WM_GetDialogItem(hItem, ID_BUTTON_4));
		  GSM_DisableButton(WM_GetDialogItem(hItem, ID_BUTTON_7));
	  }
   //USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow1(void);
void InitFocusableItem(WM_HWIN hWin);
WM_HWIN CreateWindow1(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  
  InitFocusableItem(hWin);
  
  return hWin;
}

// USER START (Optionally insert additional public code)
void InitFocusableItem(WM_HWIN hWin)
{
	fliSkip.CurrentControl = WM_GetDialogItem(hWin, ID_BUTTON_4);
	fliSkip.MainState = hWin;
	fliSkip.GuideState = NULL;

	fliPrevious.CurrentControl = WM_GetDialogItem(hWin, ID_BUTTON_5);
	fliPrevious.MainState = hWin;
	fliPrevious.GuideState = NULL;

	fliNext.CurrentControl = WM_GetDialogItem(hWin, ID_BUTTON_6);
	fliNext.MainState = hWin;
	fliNext.GuideState = NULL;

	fliFinish.CurrentControl = WM_GetDialogItem(hWin, ID_BUTTON_7);
	fliFinish.MainState = hWin;
	fliFinish.GuideState = NULL;

	SM_RegisterFocusableListItem(&fliSkip);
	SM_RegisterFocusableListItem(&fliPrevious);
	SM_RegisterFocusableListItem(&fliNext);
	SM_RegisterFocusableListItem(&fliFinish);

}
// USER END

/*************************** End of file ****************************/
