/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "globals.h"
#include "GUI.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0    (GUI_ID_USER + 0x0A)
#define ID_TEXT_0    (GUI_ID_USER + 0x0B)
#define ID_TEXT_1    (GUI_ID_USER + 0x0C)
#define ID_BUTTON_0    (GUI_ID_USER + 0x0D) //Speed Editor


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
FocusableListItem fliSpeedEditor;
bool bOriginalSpeedState = FALSE;
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 80, 100, 640, 260, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Step 7 Set Original Speed", ID_TEXT_0, 0, 0, 640, 45, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Step7Content", ID_TEXT_1, 0, 45, 640, 215, 0, 0x64, 0 },
  { BUTTON_CreateIndirect,"OriginalSpeed",ID_BUTTON_0,268, 154, 80, 20, 0, 0x64, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  WM_KEY_INFO *key_info;
  char sMotorSpeed[5];
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Step 7'
    //
	hItem = pMsg->hWin;
	WINDOW_SetBkColor(hItem, GUI_WHITE);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_32B_ASCII);
    //
    // Initialization of 'Step7Content'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetText(hItem, "Please set the original speed.");
	TEXT_SetFont(hItem, GUI_FONT_20_ASCII);
	TEXT_SetWrapMode(hItem, GUI_WRAPMODE_WORD);
	//
	// Initialization of 'OriginalSpeed'
	//
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
	BUTTON_SetText(hItem, "2500");
	BUTTON_SetFont(hItem, GUI_FONT_20_ASCII);
	// USER START (Optionally insert additional code for further widget initialization)	
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'OriginalSpeed'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;

  // USER START (Optionally insert additional message handling)
  case WM_KEY:
	  hItem = pMsg->hWin;
	  key_info = (WM_KEY_INFO*)pMsg->Data.p;
	  
	  if (bOriginalSpeedState)
	  {
		  if (key_info->PressedCnt == 0 && key_info->Key == GUI_KEY_LEFT)
		  {
			  DecreaseOriginalMotorSpeed();
			  sprintf(sMotorSpeed, "%d", iOriginalMotorSpeed);
			  BUTTON_SetText(WM_GetDialogItem(hItem, ID_BUTTON_0), sMotorSpeed);
		  }
		  else if (key_info->PressedCnt == 0 && key_info->Key == GUI_KEY_RIGHT)
		  {
			  IncreaseOriginalMotorSpeed();
			  sprintf(sMotorSpeed, "%d", iOriginalMotorSpeed);
			  BUTTON_SetText(WM_GetDialogItem(hItem, ID_BUTTON_0), sMotorSpeed);
		  }
		  else if (key_info->PressedCnt == 0 && key_info->Key == GUI_KEY_ENTER)
		  {
			  bOriginalSpeedState = FALSE;
			  BUTTON_SetPressed(WM_GetDialogItem(hItem, ID_BUTTON_0), 0);
		  }
	  }
	  else
	  {
		  if (key_info->PressedCnt == 0 && key_info->Key == GUI_KEY_ENTER)
		  {
			  bOriginalSpeedState = TRUE;
			  BUTTON_SetPressed(WM_GetDialogItem(hItem, ID_BUTTON_0), 1);
		  }
		  else
		  {
			  WM_DefaultProc(pMsg);
		  }
	  }
	  break;
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow1_7(void);
void InitFocusableItem1_7(WM_HWIN hWin);

WM_HWIN CreateWindow1_7(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, GuideMainWindow, 0, 0);
  InitFocusableItem1_7(hWin);
  return hWin;
}

// USER START (Optionally insert additional public code)
void InitFocusableItem1_7(WM_HWIN hWin)
{
	fliSpeedEditor.CurrentControl = WM_GetDialogItem(hWin, ID_BUTTON_0);
	fliSpeedEditor.MainState = GuideMainWindow;
	fliSpeedEditor.GuideState = hWin;

	SM_RegisterFocusableListItem(&fliSpeedEditor);
}
// USER END

/*************************** End of file ****************************/
