/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "globals.h"
#include "GUI.h"
#include "WM.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0    (GUI_ID_USER + 0x00)
#define ID_BUTTON_0    (GUI_ID_USER + 0x01)
#define ID_BUTTON_1    (GUI_ID_USER + 0x02)
#define ID_TEXT_0    (GUI_ID_USER + 0x04)
#define ID_BUTTON_2    (GUI_ID_USER + 0x04)
#define ID_BUTTON_3    (GUI_ID_USER + 0x05)
#define ID_BUTTON_4    (GUI_ID_USER + 0x06)
#define ID_TEXT_1    (GUI_ID_USER + 0x07)
#define ID_BUTTON_5    (GUI_ID_USER + 0x08)
#define ID_BUTTON_6    (GUI_ID_USER + 0x09)
#define ID_MULTIEDIT_0    (GUI_ID_USER + 0x0B)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 800, 480, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "GuideMain", ID_BUTTON_0, 667, 37, 80, 59, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "AlarmShow", ID_BUTTON_1, 669, 134, 80, 68, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Page1_GuideMain", ID_TEXT_0, 50, 30, 200, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Decrease", ID_BUTTON_2, 22, 451, 80, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Increase", ID_BUTTON_3, 115, 452, 80, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Confirm", ID_BUTTON_4, 207, 454, 80, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "LastStep", ID_BUTTON_5, 560, 400, 80, 45, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "NextStep", ID_BUTTON_6, 668, 400, 80, 45, 0, 0x0, 0 },
  
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;

  // USER START (Optionally insert additional variables)
  WM_KEY_INFO *key_info;
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Window'
    //
    hItem = pMsg->hWin;
    // USER START (Optionally insert additional code for further widget initialization)
	TEXT_SetFont(WM_GetDialogItem(pMsg->hWin, ID_TEXT_0), GUI_FONT_COMIC24B_1);
	WINDOW_SetBkColor(hItem, GUI_LIGHTGRAY);

	BUTTON_SetFocussable(WM_GetDialogItem(hItem, ID_BUTTON_5), 1);
	BUTTON_SetFocussable(WM_GetDialogItem(hItem, ID_BUTTON_6), 1);
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
	hItem = pMsg->hWin;
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'DataShow'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
		// USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'AlarmShow'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
		  // USER START
		  WM_HideWindow(Window1);
		  WM_ShowWindow(Window2);
		  BUTTON_SetBkColor(WM_GetDialogItem(Window2, ID_BUTTON_0), BUTTON_CI_UNPRESSED, BUTTON_GetDefaultBkColor(BUTTON_CI_UNPRESSED));
		  BUTTON_SetBkColor(WM_GetDialogItem(Window2, ID_BUTTON_1), BUTTON_CI_UNPRESSED, GUI_WHITE);
		  // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	case ID_BUTTON_2: // Notifications sent by 'Decrease'
		switch (NCode) {
		case WM_NOTIFICATION_CLICKED:
			// USER START (Optionally insert code for reacting on notification message)
			// USER END
			break;
		case WM_NOTIFICATION_RELEASED:
			// USER START (Optionally insert code for reacting on notification message)
			// USER END
			break;
			// USER START (Optionally insert additional code for further notification handling)
			// USER END
		}
		break;
	case ID_BUTTON_3: // Notifications sent by 'Increase'
		switch (NCode) {
		case WM_NOTIFICATION_CLICKED:
			// USER START (Optionally insert code for reacting on notification message)
			// USER END
			break;
		case WM_NOTIFICATION_RELEASED:
			// USER START (Optionally insert code for reacting on notification message)
			// USER END
			break;
			// USER START (Optionally insert additional code for further notification handling)
			// USER END
		}
		break;
	case ID_BUTTON_4: // Notifications sent by 'Confirm'
		switch (NCode) {
		case WM_NOTIFICATION_CLICKED:
			// USER START (Optionally insert code for reacting on notification message)
			// USER END
			break;
		case WM_NOTIFICATION_RELEASED:
			// USER START (Optionally insert code for reacting on notification message)
			// USER END
			break;
			// USER START (Optionally insert additional code for further notification handling)
			// USER END
		}
		break;
	case ID_BUTTON_5: // Notifications sent by 'LastStep'
		switch (NCode) {
		case WM_NOTIFICATION_CLICKED:
			// USER START (Optionally insert code for reacting on notification message)
			
			// USER END
			break;
		case WM_NOTIFICATION_RELEASED:
			// USER START (Optionally insert code for reacting on notification message)
			
			// USER END
			break;
			// USER START (Optionally insert additional code for further notification handling)
			// USER END
		}
		break;
	case ID_BUTTON_6: // Notifications sent by 'NextStep'
		switch (NCode) {
		case WM_NOTIFICATION_CLICKED:
			// USER START (Optionally insert code for reacting on notification message)
			// USER END
			break;
		case WM_NOTIFICATION_RELEASED:
			// USER START (Optionally insert code for reacting on notification message)
			// USER END
			break;
			// USER START (Optionally insert additional code for further notification handling)
			// USER END
		}
		break;

    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  case WM_KEY:
	  hItem = pMsg->hWin;
	  key_info = (WM_KEY_INFO*)pMsg->Data.p;
	  if (key_info->Key == GUI_KEY_LEFT || key_info->Key == GUI_KEY_UP) {
		  //WM_SetFocus(WM_GetDialogItem(hItem, ID_BUTTON_5));
		  WM_SetFocusOnPrevChild(hItem);
	  }
	  else if (key_info->Key == GUI_KEY_RIGHT || key_info->Key == GUI_KEY_DOWN) {
		  //WM_SetFocus(WM_GetDialogItem(hItem, ID_BUTTON_6));
		  WM_SetFocusOnNextChild(hItem);
	  }
	  else {
		  WM_DefaultProc(pMsg);
	  }
	  break;
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow1(void);
WM_HWIN CreateWindow1(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
