/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "globals.h"
#include "GUI.h"
// USER END

#include "DIALOG.h"



/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0    (GUI_ID_USER + 0x00)
#define ID_TEXT_0    (GUI_ID_USER + 0x01)
#define ID_TEXT_1    (GUI_ID_USER + 0x02)
#define ID_TEXT_2    (GUI_ID_USER + 0x03)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
extern GUI_CONST_STORAGE GUI_FONT GUI_FontCNFont;
//const char pdname[] = { "\xe4\xbb\x8b\xe5\x85\xa5\xe5\xbc\x8f\xe7\xa3\x81\xe5\x8a\x9b\xe7\xa6\xbb\xe5\xbf\x83\xe8\xa1\x80\xe6\xb3\xb5" };
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "LogoWindow", ID_WINDOW_0, 1, 0, 800, 480, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "PdName", ID_TEXT_0, 0, 130, 800,100, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "CpName", ID_TEXT_1, 0, 230, 800, 50, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Version", ID_TEXT_2, 0, 280, 800, 50, 0, 0x64, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
	//
	// Initialization of 'LogoWindow'
	//
	hItem = pMsg->hWin;
	WINDOW_SetBkColor(hItem, GUI_WHITE);
	//
    // Initialization of 'PdName'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
	TEXT_SetFont(hItem, &GUI_FontCNFont);
    TEXT_SetText(hItem, 
		"\xe4\xbb\x8b\xe5\x85\xa5\xe5\xbc\x8f\xe7\xa3\x81\xe5\x8a\x9b\xe7\xa6\xbb\xe5\xbf\x83\xe8\xa1\x80\xe6\xb3\xb5");//介入式磁力离心血泵
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	//
	// Initialization of 'CpName'
	//
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
	TEXT_SetFont(hItem, GUI_FONT_32_1);
	TEXT_SetText(hItem, "CardioPower");
	TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	//
	// Initialization of 'Version'
	//
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
	TEXT_SetFont(hItem, GUI_FONT_16_1);
	TEXT_SetText(hItem, "Version 1.0.0.0");
	TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindowLogo(void);
WM_HWIN CreateWindowLogo(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
