/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font Converter (Demoversion) for emWin version 5.46         *
*        Compiled Dec 12 2017, 16:37:03                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: 222.c                                                 *
* Font:        ºÚÌå                                                  *
* Height:      33                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  33                                           *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x8759 (34649)                                *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Font222;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Font222_8759[165] = { /* code 8759 */
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,
  X_____XX,X_______,_____XXX,________,_X______,
  X______X,X_______,_____XXX,________,_X______,
  X______X,X_______,______XX,________,_X______,
  X______X,X_______,XXXXXXXX,XXXXXX__,_X______,
  X______X,X_______,XXXXXXXX,XXXXXX__,_X______,
  X______X,X_______,XX______,____XX__,_X______,
  X_XXXXXX,XXXXX___,XX______,____XX__,_X______,
  X_XXXXXX,XXXXX___,XX______,____XX__,_X______,
  X_XXX__X,X__XX___,XX______,____XX__,_X______,
  X_XXX__X,X__XX___,XXXXXXXX,XXXXXX__,_X______,
  X_XXX__X,X__XX___,XXXXXXXX,XXXXXX__,_X______,
  X_XXX__X,X__XX___,XX______,________,_X______,
  X_XXX__X,X__XX___,XX______,________,_X______,
  X_XXX__X,X__XX__X,XXXXXXXX,XXXXXXX_,_X______,
  X_XXX__X,X__XX__X,XXXXXXXX,XXXXXXX_,_X______,
  X_XXXXXX,XXXXX__X,XX__XXX_,XXX__XX_,_X______,
  X_XXXXXX,XXXXX__X,XX__XXX_,XXX__XX_,_X______,
  X_XXX__X,X__XX_XX,XX__XXX_,XXX__XX_,_X______,
  X_XXX__X,X_____XX,XX__XXX_,XXX__XX_,_X______,
  X_XXX__X,X____XXX,XXXXXXXX,XXXXXXX_,_X______,
  X______X,X_XX_XX_,XXXXXXXX,XXXXXXX_,_X______,
  X______X,X_XX__X_,XX__XXX_,XXX__XX_,_X______,
  X______X,X__XX___,XX__XXX_,XXX__XX_,_X______,
  X______X,X__XX___,XX__XXX_,XXX__XX_,_X______,
  X____XXX,XXXXXX__,XX__XXX_,XXX__XX_,_X______,
  XXXXXXXX,XX__XX__,XX__XXX_,XXX__XX_,_X______,
  X_XXX___,________,XX__XXX_,XXX__XX_,_X______,
  X_______,________,XX__XXX_,____XXX_,_X______,
  X_______,________,XX______,___XXXX_,_X______,
  X_______,________,XX______,___XXX__,_X______,
  X_______,________,________,________,_X______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Font222_CharInfo[1] = {
   {  34,  34,  5, acGUI_Font222_8759 } /* code 8759 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font222_Prop1 = {
   0x8759 /* first character */
  ,0x8759 /* last character  */
  ,&GUI_Font222_CharInfo[  0] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Font222 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,33 /* height of font  */
  ,33 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Font222_Prop1}
  ,28 /* Baseline */
  ,15 /* Height of lowercase characters */
  ,23 /* Height of capital characters */
};

