/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font Converter (Demoversion) for emWin version 5.46         *
*        Compiled Dec 12 2017, 16:37:03                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: 444.c                                                 *
* Font:        ËÎÌו                                                  *
* Height:      33                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  33                                           *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x42 (66)                                     *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Font444;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_Font444_0042[ 99] = { /* code 0042, LATIN CAPITAL LETTER B */
  XXXXXXXX,XXXXXXXX,XXXXXXXX,
  X_______,________,X_______,
  X_______,________,X_______,
  X_______,________,X_______,
  X_______,________,X_______,
  XXXXXXXX,XXXX____,X_______,
  X__XX___,___XXX__,X_______,
  X__XX___,____XX__,X_______,
  X__XX___,_____XX_,X_______,
  X__XX___,_____XX_,X_______,
  X__XX___,_____XX_,X_______,
  X__XX___,_____XX_,X_______,
  X__XX___,_____XX_,X_______,
  X__XX___,____XX__,X_______,
  X__XX___,___XX___,X_______,
  X__XXXXX,XXX_____,X_______,
  X__XX___,___XX___,X_______,
  X__XX___,_____XX_,X_______,
  X__XX___,_____XX_,X_______,
  X__XX___,______XX,X_______,
  X__XX___,______XX,X_______,
  X__XX___,______XX,X_______,
  X__XX___,______XX,X_______,
  X__XX___,______XX,X_______,
  X__XX___,_____XXX,X_______,
  X__XX___,_____XX_,X_______,
  X__XX___,___XXX__,X_______,
  XXXXXXXX,XXXX____,X_______,
  X_______,________,X_______,
  X_______,________,X_______,
  X_______,________,X_______,
  X_______,________,X_______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Font444_CharInfo[1] = {
   {  17,  17,  3, acGUI_Font444_0042 } /* code 0042 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font444_Prop1 = {
   0x0042 /* first character */
  ,0x0042 /* last character  */
  ,&GUI_Font444_CharInfo[  0] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Font444 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,33 /* height of font  */
  ,33 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Font444_Prop1}
  ,28 /* Baseline */
  ,15 /* Height of lowercase characters */
  ,23 /* Height of capital characters */
};

