/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font Converter (Demoversion) for emWin version 5.46         *
*        Compiled Dec 12 2017, 16:37:03                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: CNFont-Unicode-546.c                                  *
* Font:        ºÚÌå                                                  *
* Height:      33                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  33                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: D:\[3]R&D and QA\emWin\EmWin\Font\CNFont-Unicode.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontCNFont;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontCNFontUnicode546_4ECB[165] = { /* code 4ECB */
  ________,________,________,________,________,
  ________,______X_,________,________,________,
  ________,______XX,XX______,________,________,
  ________,_____XXX,X_______,________,________,
  ________,_____XXX,XX______,________,________,
  ________,____XXXX,XXX_____,________,________,
  ________,___XXXX_,_XXX____,________,________,
  ________,___XXX__,__XXX___,________,________,
  ________,__XXX___,___XXX__,________,________,
  ________,_XXX____,____XXXX,________,________,
  ________,XXXX____,_____XXX,X_______,________,
  _______X,XXX_____,______XX,XXX_____,________,
  _____XXX,XX______,_______X,XXXXXX__,________,
  ____XXXX,X_______,________,XXXXXXX_,________,
  __XXXXX_,__XXX___,____XXX_,__XXXX__,________,
  ___XXX__,__XXX___,____XXX_,____XX__,________,
  ___XX___,__XXX___,____XXX_,________,________,
  ________,__XXX___,____XXX_,________,________,
  ________,__XXX___,____XXX_,________,________,
  ________,__XX____,____XXX_,________,________,
  ________,__XX____,____XXX_,________,________,
  ________,_XXX____,____XXX_,________,________,
  ________,_XXX____,____XXX_,________,________,
  ________,_XXX____,____XXX_,________,________,
  ________,XXX_____,____XXX_,________,________,
  ________,XXX_____,____XXX_,________,________,
  _______X,XX______,____XXX_,________,________,
  ______XX,XX______,____XXX_,________,________,
  ____XXXX,X_______,____XXX_,________,________,
  ____XXXX,________,____XXX_,________,________,
  _____XX_,________,____XXX_,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________ };

GUI_CONST_STORAGE unsigned char acGUI_FontCNFontUnicode546_5165[165] = { /* code 5165 */
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,
  X_______,________,________,________,_X______,
  X_______,__XX____,________,________,_X______,
  X_______,_XXXXX__,________,________,_X______,
  X_______,__XXXXX_,________,________,_X______,
  X_______,____XXXX,________,________,_X______,
  X_______,_____XXX,X_______,________,_X______,
  X_______,______XX,X_______,________,_X______,
  X_______,_______X,XX______,________,_X______,
  X_______,_______X,XX______,________,_X______,
  X_______,_______X,XXX_____,________,_X______,
  X_______,_______X,XXX_____,________,_X______,
  X_______,______XX,XXXX____,________,_X______,
  X_______,______XX,_XXX____,________,_X______,
  X_______,_____XXX,__XXX___,________,_X______,
  X_______,_____XXX,__XXX___,________,_X______,
  X_______,____XXX_,___XXX__,________,_X______,
  X_______,____XXX_,___XXX__,________,_X______,
  X_______,___XXX__,____XXX_,________,_X______,
  X_______,__XXXX__,____XXX_,________,_X______,
  X_______,__XXX___,_____XXX,________,_X______,
  X_______,_XXX____,_____XXX,X_______,_X______,
  X_______,XXX_____,______XX,XX______,_X______,
  X______X,XXX_____,______XX,XXX_____,_X______,
  X_____XX,XX______,_______X,XXXX____,_X______,
  X____XXX,X_______,________,XXXXX___,_X______,
  X__XXXXX,________,________,_XXXXXX_,_X______,
  X_XXXXX_,________,________,__XXXXX_,_X______,
  X_XXXX__,________,________,___XXX__,_X______,
  X__XX___,________,________,________,_X______,
  X_______,________,________,________,_X______,
  X_______,________,________,________,_X______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFontUnicode546_529B[165] = { /* code 529B */
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,
  X_______,______XX,________,________,_X______,
  X_______,______XX,X_______,________,_X______,
  X_______,______XX,X_______,________,_X______,
  X_______,______XX,X_______,________,_X______,
  X_______,______XX,X_______,________,_X______,
  X_______,______XX,X_______,________,_X______,
  X_______,______XX,X_______,________,_X______,
  X_______,______XX,X_______,________,_X______,
  X__XXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,_X______,
  X__XXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,_X______,
  X_______,______XX,X_______,___XXX__,_X______,
  X_______,______XX,X_______,___XXX__,_X______,
  X_______,______XX,X_______,___XXX__,_X______,
  X_______,______XX,X_______,___XXX__,_X______,
  X_______,______XX,________,___XXX__,_X______,
  X_______,_____XXX,________,___XX___,_X______,
  X_______,_____XXX,________,___XX___,_X______,
  X_______,_____XXX,________,___XX___,_X______,
  X_______,____XXX_,________,___XX___,_X______,
  X_______,____XXX_,________,__XXX___,_X______,
  X_______,___XXXX_,________,__XXX___,_X______,
  X_______,___XXX__,________,__XXX___,_X______,
  X_______,__XXX___,________,__XXX___,_X______,
  X_______,_XXXX___,________,__XXX___,_X______,
  X_______,XXXX____,________,__XXX___,_X______,
  X______X,XXX_____,________,_XXXX___,_X______,
  X____XXX,XX______,___X__XX,XXXX____,_X______,
  X___XXXX,X_______,____XXXX,XXXX____,_X______,
  X__XXXXX,________,____XXXX,XXX_____,_X______,
  X___XX__,________,_____XX_,________,_X______,
  X_______,________,________,________,_X______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFontUnicode546_5F0F[165] = { /* code 5F0F */
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,
  X_______,________,_XXX____,________,_X______,
  X_______,________,_XXX___X,X_______,_X______,
  X_______,________,_XXX__XX,XX______,_X______,
  X_______,________,_XXX___X,XXX_____,_X______,
  X_______,________,_XXX____,XXX_____,_X______,
  X_______,________,_XXX____,_XX_____,_X______,
  X_______,________,_XXX____,________,_X______,
  X_XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,_X______,
  X_XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,_X______,
  X_______,________,_XXX____,________,_X______,
  X_______,________,_XXX____,________,_X______,
  X_______,________,__XX____,________,_X______,
  X_______,________,__XX____,________,_X______,
  X_______,________,__XXX___,________,_X______,
  X___XXXX,XXXXXXXX,__XXX___,________,_X______,
  X___XXXX,XXXXXXXX,__XXX___,________,_X______,
  X_______,_XX_____,___XX___,________,_X______,
  X_______,_XX_____,___XXX__,________,_X______,
  X_______,_XX_____,___XXX__,________,_X______,
  X_______,_XX_____,____XX__,________,_X______,
  X_______,_XX_____,____XXX_,________,_X______,
  X_______,_XX_____,____XXX_,________,_X______,
  X_______,_XX_____,_X___XXX,____X___,_X______,
  X_______,_XX___XX,XX___XXX,_____XX_,_X______,
  X_______,_XXXXXXX,XX____XX,X___XXXX,_X______,
  X____XXX,XXXXXX__,______XX,XX__XXX_,_X______,
  X__XXXXX,XX______,_______X,XXX_XXX_,_X______,
  X__XXXX_,________,________,XXXXXXX_,_X______,
  X__XX___,________,________,_XXXXX__,_X______,
  X_______,________,________,___XXX__,_X______,
  X_______,________,________,________,_X______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFontUnicode546_5FC3[165] = { /* code 5FC3 */
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,
  X_______,_______X,________,________,_X______,
  X_______,_____XXX,X_______,________,_X______,
  X_______,______XX,X_______,________,_X______,
  X_______,_______X,XX______,________,_X______,
  X_______,_______X,XXX_____,________,_X______,
  X_______,________,XXX_____,________,_X______,
  X_______,________,XXXX____,________,_X______,
  X_______,________,_XX_____,________,_X______,
  X_______,________,________,________,_X______,
  X_______,___XXX__,________,________,_X______,
  X_______,___XXX__,________,_XX_____,_X______,
  X___XXX_,___XXX__,________,XXX_____,_X______,
  X___XXX_,___XXX__,________,_XXX____,_X______,
  X___XXX_,___XXX__,________,_XXXX___,_X______,
  X___XXX_,___XXX__,________,__XXX___,_X______,
  X___XXX_,___XXX__,________,___XXX__,_X______,
  X__XXX__,___XXX__,________,___XXXX_,_X______,
  X__XXX__,___XXX__,________,____XXX_,_X______,
  X__XXX__,___XXX__,________,____XXX_,_X______,
  X__XXX__,___XXX__,________,_____X__,_X______,
  X_XXX___,___XXX__,________,________,_X______,
  X_XXX___,___XXX__,________,________,_X______,
  X_XXX___,___XXX__,________,X_______,_X______,
  X_______,___XXX__,________,XXX_____,_X______,
  X_______,___XXX__,________,XXX_____,_X______,
  X_______,___XXX__,_______X,XX______,_X______,
  X_______,___XXXX_,_______X,XX______,_X______,
  X_______,___XXXXX,XXXXXXXX,XX______,_X______,
  X_______,____XXXX,XXXXXXXX,X_______,_X______,
  X_______,________,________,________,_X______,
  X_______,________,________,________,_X______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFontUnicode546_6CF5[165] = { /* code 6CF5 */
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,
  X_______,________,________,________,_X______,
  X__X____,________,________,________,_X______,
  X__XXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,_X______,
  X__XXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,_X______,
  X_______,____XXX_,________,________,_X______,
  X_______,___XXXX_,________,________,_X______,
  X_______,___XXX__,________,________,_X______,
  X_______,__XXXXXX,XXXXXXXX,XXX_____,_X______,
  X_______,XXXXXXXX,XXXXXXXX,XXX_____,_X______,
  X______X,XXX_____,________,_XX_____,_X______,
  X____XXX,XXX_____,________,_XX_____,_X______,
  X___XXXX,_XX_____,________,_XX_____,_X______,
  X_XXXXX_,_XX_____,________,_XX_____,_X______,
  X__XX___,_XXXXXXX,XXXXXXXX,XXX_____,_X______,
  X_______,_XXXXXXX,XXXXXXXX,XXX_____,_X______,
  X_______,________,XXX_____,________,_X______,
  X_______,________,XXX_____,__X_____,_X______,
  X_______,________,XXXX____,_XXX____,_X______,
  X__XXXXX,XXXXXX__,XXXX____,XXXXX___,_X______,
  X__XXXXX,XXXXXX__,XX_XX__X,XXX_____,_X______,
  X_______,___XX___,XX_XXXXX,X_______,_X______,
  X_______,__XXX___,XX__XXXX,________,_X______,
  X_______,_XXX____,XX__XXX_,________,_X______,
  X_______,XXXX____,XX___XXX,________,_X______,
  X______X,XXX_____,XX____XX,X_______,_X______,
  X____XXX,XX______,XX_____X,XXX_____,_X______,
  X__XXXXX,________,XX______,_XXXXXX_,_X______,
  X__XXXX_,_______X,XX______,__XXXX__,_X______,
  X__XX___,_____XXX,XX______,____XX__,_X______,
  X_______,_____XXX,X_______,________,_X______,
  X_______,________,________,________,_X______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFontUnicode546_78C1[165] = { /* code 78C1 */
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,
  X_______,________,________,__X_____,_X______,
  X_______,________,XXX_____,__XXX___,_X______,
  X_______,________,_XX_____,_XXX____,_X______,
  X_XXX___,___XX___,_XXX____,_XX_____,_X______,
  X_XXXXXX,XXXXX___,__XX____,_XX_____,_X______,
  X_XXXXXX,XXXXX___,__X_____,XXX_____,_X______,
  X_____XX,X____XXX,XXXXXXXX,XXXXXXXX,_X______,
  X_____XX,_____XXX,XXXXXXXX,XXXXXXXX,_X______,
  X_____XX,________,________,________,_X______,
  X____XXX,________,_XX_____,_X______,_X______,
  X____XX_,________,XXX_____,_XXX____,_X______,
  X____XX_,________,XXX_____,_XX_____,_X______,
  X___XXX_,________,XX______,XXX_____,_X______,
  X___XXXX,XXXX___X,XX__X___,XX______,_X______,
  X__XXXXX,XXXX___X,X___XX__,XX__XXX_,_X______,
  X_XXXXX_,__XX__XX,X__XXX_X,X___XXX_,_X______,
  X_XX_XX_,__XX__XX,___XX__X,X___XX__,_X______,
  X_XX_XX_,__XX_XXX,__XXX_XX,XXXXXX__,_X______,
  X_X__XX_,__XXXXXX,XXXX__XX,XXXXX___,_X______,
  X____XX_,__XX_XXX,XXXX____,___XX___,_X______,
  X____XX_,__XX____,_XX_____,__XX____,_X______,
  X____XX_,__XX____,_XX_____,__XX____,_X______,
  X____XX_,__XX____,XX______,_XX_____,_X______,
  X____XXX,XXXX____,XX_XX___,_XX_XX__,_X______,
  X___XXXX,XXXX___X,X__XX___,XXX_XX__,_X______,
  X___XXX_,__XX__XX,___XX___,XX__XXX_,_X______,
  X___XXX_,__XX_XXX,___XXX_X,XXXXXXX_,_X______,
  X___XXX_,____XXXX,XXXXXXXX,XXXXXXX_,_X______,
  X_______,_____XXX,XXX_XX_X,XX___XX_,_X______,
  X_______,________,____XX__,_____XX_,_X______,
  X_______,________,________,________,_X______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFontUnicode546_79BB[165] = { /* code 79BB */
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,
  X_______,______XX,X_______,________,_X______,
  X_______,_______X,XX______,________,_X______,
  X_______,_______X,XX______,________,_X______,
  X_XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,_X______,
  X_XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,_X______,
  X_______,________,_____X__,________,_X______,
  X_______,___XXX__,___XXXXX,________,_X______,
  X____XXX,__XXXXXX,__XXXX__,________,_X______,
  X____XXX,_____XXX,XXXX____,__XX____,_X______,
  X____XXX,______XX,XXXXX___,__XX____,_X______,
  X____XXX,___XXXXX,___XXXXX,__XX____,_X______,
  X____XXX,__XXXX__,_____XXX,__XX____,_X______,
  X____XXX,___X____,______X_,__XX____,_X______,
  X____XXX,XXXXXXXX,XXXXXXXX,XXXX____,_X______,
  X____XXX,XXXXXXXX,XXXXXXXX,XXXX____,_X______,
  X_______,_______X,________,________,_X______,
  X_______,______XX,XX______,________,_X______,
  X_______,______XX,X_______,________,_X______,
  X__XXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,_X______,
  X__XXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,_X______,
  X__XXX__,____XXX_,________,____XX__,_X______,
  X__XXX__,____XX__,_____X__,____XX__,_X______,
  X__XXX__,___XX___,____XXX_,____XX__,_X______,
  X__XXX__,_XXXX___,_____XXX,____XX__,_X______,
  X__XXX__,_XXXXXXX,XXXXXXXX,X___XX__,_X______,
  X__XXX__,_XXXXXXX,XXX___XX,X___XX__,_X______,
  X__XXX__,_XXX____,________,____XX__,_X______,
  X__XXX__,________,________,___XXX__,_X______,
  X__XXX__,________,________,XXXXXX__,_X______,
  X__XXX__,________,________,_XXXX___,_X______,
  X_______,________,________,________,_X______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFontUnicode546_8840[165] = { /* code 8840 */
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,
  X_______,________,________,________,_X______,
  X_______,_____X__,________,________,_X______,
  X_______,_____XXX,________,________,_X______,
  X_______,____XXX_,________,________,_X______,
  X_______,____XXX_,________,________,_X______,
  X_______,____XX__,________,________,_X______,
  X____XXX,XXXXXXXX,XXXXXXXX,XXXX____,_X______,
  X____XXX,XXXXXXXX,XXXXXXXX,XXXX____,_X______,
  X____XX_,____XX__,___XX___,_XXX____,_X______,
  X____XX_,____XX__,___XX___,_XXX____,_X______,
  X____XX_,____XX__,___XX___,_XXX____,_X______,
  X____XX_,____XX__,___XX___,_XXX____,_X______,
  X____XX_,____XX__,___XX___,_XXX____,_X______,
  X____XX_,____XX__,___XX___,_XXX____,_X______,
  X____XX_,____XX__,___XX___,_XXX____,_X______,
  X____XX_,____XX__,___XX___,_XXX____,_X______,
  X____XX_,____XX__,___XX___,_XXX____,_X______,
  X____XX_,____XX__,___XX___,_XXX____,_X______,
  X____XX_,____XX__,___XX___,_XXX____,_X______,
  X____XX_,____XX__,___XX___,_XXX____,_X______,
  X____XX_,____XX__,___XX___,_XXX____,_X______,
  X____XX_,____XX__,___XX___,_XXX____,_X______,
  X____XX_,____XX__,___XX___,_XXX____,_X______,
  X____XX_,____XX__,___XX___,_XXX____,_X______,
  X____XX_,____XX__,___XX___,_XXX____,_X______,
  X____XX_,____XX__,___XX___,_XXX____,_X______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,_X______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,_X______,
  X_______,________,________,________,_X______,
  X_______,________,________,________,_X______,
  X_______,________,________,________,_X______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontCNFontUnicode546_CharInfo[9] = {
   {  34,  34,  5, acGUI_FontCNFontUnicode546_4ECB } /* code 4ECB */
  ,{  34,  34,  5, acGUI_FontCNFontUnicode546_5165 } /* code 5165 */
  ,{  34,  34,  5, acGUI_FontCNFontUnicode546_529B } /* code 529B */
  ,{  34,  34,  5, acGUI_FontCNFontUnicode546_5F0F } /* code 5F0F */
  ,{  34,  34,  5, acGUI_FontCNFontUnicode546_5FC3 } /* code 5FC3 */
  ,{  34,  34,  5, acGUI_FontCNFontUnicode546_6CF5 } /* code 6CF5 */
  ,{  34,  34,  5, acGUI_FontCNFontUnicode546_78C1 } /* code 78C1 */
  ,{  34,  34,  5, acGUI_FontCNFontUnicode546_79BB } /* code 79BB */
  ,{  34,  34,  5, acGUI_FontCNFontUnicode546_8840 } /* code 8840 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontCNFontUnicode546_Prop9 = {
   0x8840 /* first character */
  ,0x8840 /* last character  */
  ,&GUI_FontCNFontUnicode546_CharInfo[  8] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontCNFontUnicode546_Prop8 = {
   0x79BB /* first character */
  ,0x79BB /* last character  */
  ,&GUI_FontCNFontUnicode546_CharInfo[  7] /* address of first character */
  ,&GUI_FontCNFontUnicode546_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontCNFontUnicode546_Prop7 = {
   0x78C1 /* first character */
  ,0x78C1 /* last character  */
  ,&GUI_FontCNFontUnicode546_CharInfo[  6] /* address of first character */
  ,&GUI_FontCNFontUnicode546_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontCNFontUnicode546_Prop6 = {
   0x6CF5 /* first character */
  ,0x6CF5 /* last character  */
  ,&GUI_FontCNFontUnicode546_CharInfo[  5] /* address of first character */
  ,&GUI_FontCNFontUnicode546_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontCNFontUnicode546_Prop5 = {
   0x5FC3 /* first character */
  ,0x5FC3 /* last character  */
  ,&GUI_FontCNFontUnicode546_CharInfo[  4] /* address of first character */
  ,&GUI_FontCNFontUnicode546_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontCNFontUnicode546_Prop4 = {
   0x5F0F /* first character */
  ,0x5F0F /* last character  */
  ,&GUI_FontCNFontUnicode546_CharInfo[  3] /* address of first character */
  ,&GUI_FontCNFontUnicode546_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontCNFontUnicode546_Prop3 = {
   0x529B /* first character */
  ,0x529B /* last character  */
  ,&GUI_FontCNFontUnicode546_CharInfo[  2] /* address of first character */
  ,&GUI_FontCNFontUnicode546_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontCNFontUnicode546_Prop2 = {
   0x5165 /* first character */
  ,0x5165 /* last character  */
  ,&GUI_FontCNFontUnicode546_CharInfo[  1] /* address of first character */
  ,&GUI_FontCNFontUnicode546_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontCNFontUnicode546_Prop1 = {
   0x4ECB /* first character */
  ,0x4ECB /* last character  */
  ,&GUI_FontCNFontUnicode546_CharInfo[  0] /* address of first character */
  ,&GUI_FontCNFontUnicode546_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontCNFont = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,33 /* height of font  */
  ,33 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontCNFontUnicode546_Prop1}
  ,28 /* Baseline */
  ,15 /* Height of lowercase characters */
  ,23 /* Height of capital characters */
};

