/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font Converter (Demoversion) for emWin version 5.26         *
*        Compiled Aug  8 2014, 14:06:18                              *
*                                                                    *
*        (c) 1998 - 2014 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: CNFont.c                                              *
* Font:        ºÚÌå                                                  *
* Height:      33                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  33                                           *
* Range disabled:       0000 - FFFF                                  *
* Range enabled:        4ECB - 4ECB                                  *
* Range enabled:        4ECB - 4ECB                                  *
* Range enabled:        4ECB - 4ECB                                  *
* Range disabled:       0000 - FFFF                                  *
* Range enabled:        4ECB - 4ECB                                  *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: D:\[3]R&D and QA\emWin\EmWin\Icon\jin.c         *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: D:\[3]R&D and QA\emWin\EmWin\Icon\CNFont-Unicode.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"
#include "globals.h"
#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontCNFont;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontCNFont_4ECB[132] = { /* code 4ECB */
  __XX_X__,XX____XX,_X_XX___,XX_X___X,
  XXX_XXXX,___XXX_X,X_XX_XXX,XXXX___X,
  _X____X_,_X____X_,XX_X__X_,X___X__X,
  __XXXX_X,X____X_X,X_X___X_,__XX____,
  _____X_X,XXX_XXXX,XX_X_XX_,XX__XX_X,
  XXXXX___,___XX___,__XXXXXX,XX__XXXX,
  _XXX__XX,_XX_XX_X,XXX_XXXX,X_X__XX_,
  XX_XX_XX,XX_X_X_X,__XX___X,X_XXX__X,
  _X_XXX__,___X___X,X___X___,X___X_X_,
  ____XXXX,_XX_____,XX_X__XX,__X__X__,
  _X___X__,__X_XX__,XXXXX__X,XXX_X__X,
  _____XX_,____XX__,___X___X,____X_X_,
  XXX__X_X,_XXXXXX_,X_XX__X_,_X_X_XX_,
  ___X_X__,XXXX___X,_X____X_,__XXX_XX,
  XXX_XXX_,_X____XX,XX____X_,_____XX_,
  X____XX_,_X_XX__X,X___X_XX,XX_X___X,
  XXX_XX_X,__X_____,XX____X_,__XX_X_X,
  XX__X__X,______XX,X__XX_X_,XXX___X_,
  __XX___X,__XX__XX,____XX__,_X__XX_X,
  ___XX_XX,X__XXXX_,X__X_XXX,__X_X_XX,
  _X_XXX_X,___XXXXX,X_XXX___,____XX_X,
  XX_X_XX_,X____X_X,____X_X_,XXXX_X__,
  X_X_X__X,X___XX_X,_XXX_X_X,X_XXX_XX,
  X_XXXX__,_X_XX_XX,____X___,XXX___X_,
  X_X__XXX,XXX____X,XX__X___,_XX_XXX_,
  __X_X_XX,XXXXXXXX,_XX__X__,__XX_XXX,
  XXXXXXXX,_X_XXX_X,X_XX___X,_X__X__X,
  ______XX,X__X____,__X__X__,_______X,
  _X_X_X__,X___XX__,_XX_X___,XXXX__X_,
  __XX____,XXXXX___,_XX__XXX,_XX_____,
  __XXXXXX,X_XX____,X_______,XXXXXXXX,
  X_X____X,XX_X_X__,_X_XXXXX,_XX_XXX_,
  ___X_XXX,_X_X___X,X___XX_X,__XXXX_X};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFont_5165[132] = { /* code 5165 */
  XX__X_XX,X___XXX_,____X___,X_X_XX_X,
  XXX_X___,_XXX_X_X,_____XX_,XXX_X__X,
  __XXXX__,___X__X_,__XX_XXX,_X_XX___,
  X_XX_X__,_X_XXX__,__X___X_,X_XX___X,
  XX_X___X,____X_XX,X_XXX_XX,X_X___XX,
  _XX_____,XXXXX_X_,__XXXX__,_X_XXXXX,
  X_XXXXX_,_X___XX_,XXX_XX_X,_X_X_X__,
  __XXXXX_,X_____X_,_____XXX,XX_X__X_,
  _____X_X,XXXX__XX,_X___X_X,XX__X___,
  __X_XXXX,__X_X_XX,XXXXX_X_,X____X_X,
  __X__X_X,X__XXXXX,X__X___X,_XXX__X_,
  X___XX_X,XXXXXX_X,__X_X___,XXX_X_X_,
  ___X_XXX,_XXX_XX_,XX_X__XX,XXXXXXX_,
  X____XX_,XX_X_X__,____XXXX,_XXXX_XX,
  X___XXXX,_X__XXX_,_XX_XXX_,__XXXX_X,
  XX___XX_,__X__XXX,_X_X_XXX,XX__X__X,
  XXX__XXX,_____X__,X_XXXX_X,___XXXX_,
  __XX___X,X____X__,XX_XX__X,__X____X,
  X_XX__X_,X_XX_X_X,______X_,_X___XXX,
  _XX__XXX,__X_XX__,_XX_XX__,_X_X_X_X,
  XXXX_XXX,_____XXX,XX_XXXX_,__X_X___,
  X__X___X,X___X_X_,XXX___X_,XXXX_XXX,
  X__X__X_,XX__X___,XX_XX__X,___XXXXX,
  XXX__XXX,XXXX_XX_,___XXX_X,___X__X_,
  ______XX,__X_XX__,X_XX___X,X__XX_XX,
  XXXX_XX_,XX__X_X_,_XX_XX__,X_X____X,
  XX__X_XX,__XX__XX,_X_XX___,__X_XX_X,
  _X_X_XXX,X__XXXXX,X_X__XXX,____XXX_,
  ___X___X,X_X____X,__X_____,X___XX_X,
  _X_XXXX_,X_X__XXX,_X_X_X_X,X__X_XXX,
  X__XX__X,_X____XX,XX__X_XX,__X__X__,
  ___XXXXX,XX___XX_,___X_XXX,_XX_XX_X,
  X______X,_X_XX__X,XX_XXX__,_X___X_X};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFont_529B[132] = { /* code 529B */
  X______X,XXXX_XX_,X__X___X,X____X_X,
  XX___XX_,X_X_X__X,XXX_XX_X,___X_X__,
  XX_XX_X_,XX_XXXXX,X_XX_X_X,XX_XXX_X,
  X__XX_XX,XX_XXX__,_X__XX__,_X_XX__X,
  _X__X___,_X__X__X,XXX_____,__XX__XX,
  X_X__X__,_X___X_X,_XX_X_X_,__X_XX__,
  X__X_XXX,_____XXX,_X_X__XX,__XXXXX_,
  _XX__X__,X_X_____,X____X__,X_______,
  ____XXXX,X_XXX__X,__X__XX_,__XXX__X,
  XX_XX__X,X_X_X__X,_XX_XXX_,X__XXXX_,
  X_X___X_,_XX__XX_,XXXXXX_X,X_X___X_,
  _XXXX_XX,X_X_XX_X,_____X_X,X__X_XX_,
  ____XX_X,_X_X_XXX,___XXX_X,X_XX_XXX,
  X_XXXX_X,XX__XX_X,XXXXX__X,_X_XX_XX,
  X_XX_XX_,X__X_X__,X_XXX__X,XXX__X_X,
  X____XX_,XX_X_XXX,_XX_X___,_XXX__X_,
  _X_XX_X_,X__X_XXX,_X_XX_XX,_XXXX__X,
  XXX_____,__X__XX_,XX_XXX__,X_XXXXXX,
  ______X_,X_XX_XXX,X_XX_XXX,__XXX__X,
  X___XX_X,_X_X____,_XX_X__X,_____XX_,
  XXXX__X_,__XXX__X,__X_XXX_,X__X_XXX,
  X_X___X_,_X_XX_XX,X_X_XXXX,_XXX__XX,
  _X__XX__,_XX__X_X,X_X_X_XX,XX_XX_X_,
  _XX_____,X_X_XXXX,____XX_X,XXX_XXXX,
  XX__X___,XX__X__X,XXXXX_X_,XX_XXX_X,
  XXXXXX_X,X_X__X__,XX__XXXX,XX___X_X,
  _XXXX_XX,___X_X__,X_XX__XX,_XX___X_,
  _X__XXXX,__X___X_,X_XXXX_X,XX_____X,
  XXXX____,__XX_X__,XX____XX,_XXXX_XX,
  XX_XX_X_,_X_X____,___XXX__,_X__X___,
  _XX__X_X,XXX__X_X,XXX___X_,_______X,
  X_X_X___,_X_XX_X_,_X____XX,__X_X__X,
  X____XXX,_XX__X_X,_X__XX__,_XXXX__X};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFont_5F0F[132] = { /* code 5F0F */
  XXX_XXXX,X_X_X_X_,_XX_X___,XXX_X___,
  XX_X__XX,XX______,_XXXX__X,__XXXX_X,
  X_X_X_XX,_X__XXXX,XX_X_X__,__XX_X_X,
  __X__XXX,_X__X_X_,_XXX_XXX,_X_XXXXX,
  XX__XX_X,XX_X__X_,X__X_XX_,_XX_____,
  X__X_X_X,___X_X__,X_X_X___,_X_X__X_,
  _X__XXX_,__XX_XXX,X_XXX_XX,XXXXXX__,
  _XXX____,_X__X_X_,X_XX___X,_XXXX__X,
  XX_X__X_,__XXX_X_,XXXXX_X_,XX_XX_X_,
  XXX___X_,___X___X,_XX_X_XX,XX__XXX_,
  _X__X___,X_XXXXX_,XX_XX___,XXX_X_X_,
  __X_X__X,_X___X__,XX______,XX_XXXXX,
  XX_X_X__,_X_XXXX_,__X____X,______XX,
  X__XXX_X,X____XXX,X_X_XX__,____XX_X,
  X_X_XX__,_X___X__,X_XX_XX_,__XXX_X_,
  _XXX_XX_,___XXX__,_____XX_,X__X_X_X,
  XX__X__X,XXXX___X,X_X_X__X,XX_X__XX,
  __X_X___,__XX____,__X___XX,XX_X_X_X,
  X____X__,XX____XX,__X__X_X,_XX_XXX_,
  XXXXXXX_,__X___X_,X__XXX_X,_XXXX_XX,
  XXX_X__X,_XXXXX__,__XX__X_,X__XX_XX,
  __X__X__,XXX__XX_,_XX__XX_,X_XX_XX_,
  _XX_XX__,X_XX___X,XX_XX_X_,X____XXX,
  __X_X__X,__XX__X_,___XXXXX,X_XX___X,
  XX_X_X__,XXXX_XXX,____XXX_,X_X_X__X,
  X_______,XXX___X_,_XX_____,____X_X_,
  _XX__XX_,X_XX_X_X,_X__X_XX,X_XXX__X,
  X___X__X,X_XXXXXX,__X_XXX_,_X_X_XXX,
  XXXX_XX_,XXXX__XX,X__X____,X_XX_X__,
  _X___X__,_XXX_XX_,__XX_X__,XXX_XX_X,
  ____X_X_,XX__X__X,X_____XX,XX___X_X,
  X_X_XXXX,_XXXX_X_,XXXXX_X_,__XX___X,
  X_X_XX_X,_XXXXX_X,X__XXX__,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFont_5FC3[132] = { /* code 5FC3 */
  X_XX___X,_X_X__XX,XXX_XX__,_XXX___X,
  ________,_XX_XX__,______XX,XXXX___X,
  _____XXX,XX_X_X_X,X_____XX,X____XXX,
  XXX_XXXX,_XX_X__X,_______X,XX___X__,
  XXXXXX__,X_X__XXX,__XXXX__,__XX__X_,
  XXX_X___,X__XXX__,_XX_XXXX,___X____,
  XXXXX_X_,_X___X_X,_X__XX_X,X__X_X_X,
  X_XX__X_,XXXXX__X,__X__X_X,X_X___X_,
  _X_XX__X,X_____X_,X____XX_,__X___X_,
  X_______,___XX__X,_XXXXXX_,_____XX_,
  _X_X__X_,XXXXX_XX,_XXX_XX_,X_X___XX,
  XXXX__X_,_XX_X__X,_XXX_XX_,XXX_XXXX,
  X__X_X_X,________,_XXXXXX_,_X_X___X,
  _XX__X_X,_XX___XX,______XX,X___XXX_,
  __XX_X_X,X___X_XX,XXXX____,XXXXX__X,
  X_X_X_XX,XXXX__X_,__XX_XXX,X__XXXXX,
  _XX_X___,__X___XX,XX_X_X__,XXX_XX_X,
  _XX__XX_,_XXX____,X_XX__X_,X_____X_,
  X__XXX__,X_X__X_X,XX_____X,_____XXX,
  XX_____X,XXX__XXX,XXXX_X__,XX_X_XXX,
  __X__XXX,XX_X___X,X_XX___X,XX__X_X_,
  X____XXX,______X_,_X_XX_X_,_X__X_XX,
  ______XX,X_X__X_X,_____X_X,_X_XX__X,
  X_XXXXX_,_XX__X__,X__X____,XX_X_X_X,
  X_X_____,XXXX___X,XX_XXX__,XX_X_XX_,
  X____X__,X____XX_,XX_XX_X_,_X_X_X_X,
  X___X_XX,X___X___,XXXXXX_X,X____XXX,
  _X_XXX__,_XX__X_X,_XX__XXX,XX_XXX__,
  __X_X_X_,_XX____X,X_XXX__X,X__X_X_X,
  _XXX__XX,XXXXXXX_,XXXX_X__,X_XXXX_X,
  XX_XXX__,XXXXX__X,__XXXXXX,_X_XXX_X,
  X____X_X,XXX_XXX_,______XX,_XX__X__,
  X__XX___,XX______,X__XXXX_,____XX_X};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFont_6CF5[132] = { /* code 6CF5 */
  _XX__X__,XXXXX_XX,XX_X_XXX,X___X__X,
  _X__XX__,XX___XX_,____XXX_,XXX_X_XX,
  _____X__,_XX_X_X_,XX_X____,X_XXXX__,
  XX____X_,__X_____,XXX_X_XX,XXX_XXX_,
  X_XX___X,X___XXXX,X_XX____,_XXXX___,
  X__XX_X_,XX_X_XX_,X__XX_X_,XXXXX__X,
  X__XX__X,XXX_XXX_,_XXX___X,_X__XXX_,
  __XXX__X,_______X,_X_X____,_X_X__X_,
  X_X_X_XX,____X_X_,__X___XX,_X__XXX_,
  _XXX__X_,_XX_X___,X_X___XX,_X__XXXX,
  __XXX_XX,XXXXX_X_,XX____X_,X_____XX,
  XXXX__X_,X__X__XX,XXX___XX,__XXXX_X,
  _X_X_XXX,XXXX____,XX_XXX_X,XXX___X_,
  ____XX_X,X_XXX___,_XX_XX_X,_X_XX__X,
  X____XX_,_XX____X,XXXX_XX_,__XX_XXX,
  _X____XX,X__X____,_X_XX__X,__X____X,
  _X__X_XX,_XXX_XXX,_X__X_XX,XXXXXXX_,
  __XX_X_X,__XX_XXX,___X_XX_,_X__XXXX,
  __X___X_,_XXX_X__,_XX_X__X,X_X_X_XX,
  ___XX_XX,_X____X_,X_X____X,_XX___X_,
  X_XX_XXX,_______X,X____X_X,__XX_XXX,
  _X____X_,X_XX_XX_,XX_X____,_____X_X,
  X_XXXXXX,XX____XX,_XX__X_X,___XXX_X,
  XXX_X_XX,_XX___X_,____X_XX,X_XXX_X_,
  X_X_XX_X,_____X_X,_____XX_,__XX___X,
  XXX___X_,___XX__X,XXX____X,XXX_X_XX,
  __XXXX_X,_XXX_XX_,XXXXXXXX,X__X____,
  X_X___XX,XXX___X_,_XX_XXXX,XX_XX__X,
  _XXX___X,_XX_XX_X,_XX_X__X,XXXX___X,
  XXXX_X__,_X__X_X_,XXX__X_X,X_X____X,
  X_X___X_,XX__XX_X,XX_X_XXX,___XX___,
  X___X_X_,XXX__XXX,_X____XX,XXX__X_X,
  _XX_XXXX,XXX_____,_XXXX___,XXX__X_X};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFont_78C1[132] = { /* code 78C1 */
  XXXXXX__,___X_X_X,XX_XXX__,X____XXX,
  _____X__,XXXXXXXX,X___XXX_,XX_X____,
  X_X___X_,__XX__XX,_X___XXX,X_____X_,
  X__XX_XX,___XX___,__X__X__,_____X__,
  X_XX___X,_X___X_X,___XXXX_,X______X,
  X_XX___X,_X_X_X_X,XX_X_XX_,__X___X_,
  ___X__X_,___X_XX_,_X___X_X,___XXXX_,
  X___X_XX,X__XX__X,X_XX_X_X,_XX___X_,
  __XXX__X,_XX_X_XX,__X_XX_X,__X__XXX,
  ___X___X,_XXXX__X,____XX_X,_XX_X_XX,
  _X_XX___,XXX_____,___X_X__,XX_XXX_X,
  _XXXXXX_,XXX___XX,_X_XXX__,X___X_XX,
  _XX_XXX_,__X_X_XX,X_XXX_XX,_____X_X,
  XX__XX__,_X_X__X_,_XX____X,_X__X_X_,
  __XXX_XX,X____XXX,X___XXXX,_X__XX_X,
  _XX_X__X,XXX_XX__,XX_XXX_X,X_XX_XX_,
  ____XXXX,_X___X__,X_____XX,X_X___XX,
  ____XXX_,_XXX__XX,X__XXXXX,_X____XX,
  _XXX____,XX______,_X_XXX__,____XXX_,
  XXXXXX__,X__X_XX_,XXXX___X,_X_XXXXX,
  _XX_X___,__XX_X_X,_X__XXXX,_XX_X__X,
  XX___X_X,XX_XX___,XXXX__XX,_XXX___X,
  XX__X_XX,XXX__X_X,X____XXX,XX_X__X_,
  XXX__XXX,___X__XX,XX_____X,XXX_X__X,
  XX______,X___X_X_,__XX_XX_,X____XXX,
  __X__XXX,XXX__X_X,__X_X___,__X__X__,
  X______X,___XX__X,_X_XX_X_,__XX_X_X,
  ___XXX__,XXX_XXX_,X_XXXXXX,___XXX__,
  X_XXXXXX,_X_XX__X,XXXX____,XX__X__X,
  XX_XX_X_,_X_XX_X_,X___X___,_X_X___X,
  XXX___XX,_XXX_X__,XX_X_X_X,X___X__X,
  _____XXX,_XX___XX,__X_XX__,____X__X,
  X__X_XXX,X_XX__X_,_X_____X,__X__XXX};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFont_79BB[132] = { /* code 79BB */
  __XXX_X_,_XX_XX__,__X_X_XX,___XXX__,
  X_X_X__X,X_X_X___,X__X____,XXX_X_X_,
  XXXXX_X_,___XX_XX,XX____XX,X_______,
  X_X____X,_X_X__X_,XX___X_X,_X__XX_X,
  XXX___X_,_X_X_XX_,____XXX_,_XX_X_X_,
  ___XX_X_,X____X_X,X__XXXX_,XXXX__X_,
  XXXX___X,___XXXX_,_X___X__,X__XXXX_,
  ___X___X,XXXXXX__,XX_XX___,_XXXX_XX,
  __X_____,_XX_XXX_,X__XX__X,___X_XXX,
  __X_X___,_XX_XXXX,XX_XX___,X_XX___X,
  ___XX___,_XXX_X__,X___X_X_,_X_X_XXX,
  XX___XX_,__X_XX__,___XXXX_,_XX_X__X,
  XXXXXX_X,XX_X_X__,X__XXX_X,__X__XX_,
  X__XX___,_____X__,___XX_X_,__X_XX_X,
  __XX__X_,XXXXXXXX,___XX___,_X_XX_X_,
  _X__XXX_,XX_X__XX,_XX_XX_X,XX_XXXXX,
  _X_XXX_X,XXX_____,____XXX_,__X_XXXX,
  _X_X____,XX_XXXXX,XX__X_X_,XX____X_,
  XX_X_X__,_____X_X,_XX__XX_,X_XX__XX,
  ___X___X,X_____X_,X_XXX_XX,X______X,
  XXX__X__,_X__X_XX,__X_XXX_,_____X_X,
  X_X____X,XX_X_XX_,_X_X____,_XX_XXX_,
  XX_X_XX_,X_______,_XXXXX_X,X____X_X,
  XX__X___,X___XX_X,X_____X_,_XXXXXXX,
  _X__XXX_,_X____X_,_XX_XX_X,_X__XX__,
  XXXXX___,____XXX_,X_______,_X__XX_X,
  __XX_XX_,XXXXX__X,__X___X_,_XX__X__,
  ___XXXXX,XX__XXXX,____XXX_,X_X__X_X,
  XX_X___X,_X__X__X,__X_X___,X_XXXX_X,
  _X__XX_X,_XX__XXX,__XXX___,XX_X_X_X,
  __XX_X__,XXXX____,X_XX__XX,_X_____X,
  X_XXXX_X,X_X____X,__XX_XXX,_XXXX_XX,
  _X_X__XX,_X__XXXX,XXXX_XXX,_XXX_X__};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFont_8840[132] = { /* code 8840 */
  XX__X__X,__X_XXXX,_X___X_X,___X_XX_,
  XX_X____,X___X___,_X_XX_XX,XXX_X___,
  XX__X_X_,XXXX___X,XXXX___X,__X____X,
  XX__XXX_,XX_____X,X__XX__X,XX_X_XX_,
  _XXXXX_X,__X__XX_,__X_X_X_,X___X_X_,
  XXXX_X__,__X_XX_X,XX_XX_XX,XXXX_XX_,
  _XXX__X_,_XX_XXXX,______X_,X__X_XXX,
  _XX_X_X_,XX_X_X_X,_XX__XX_,_X_XX_XX,
  __X___XX,XXXXXX__,_X__XXXX,XXX_XX_X,
  ___X____,XX_XXXXX,XXXX_XXX,__XXX_XX,
  XX__XX__,X_XXXXXX,XX___X_X,X______X,
  _X_X_XXX,_X___XXX,____X_X_,XXX_XXX_,
  X__X_X__,X__X_XXX,_XX_____,XX_X___X,
  ___XX_X_,_X_XX___,XX___XX_,__X_XXX_,
  _XX_____,_X_X____,XXXXX___,X_XX_XXX,
  _XXX_X_X,_X_X__XX,XX_X____,_X_XX_XX,
  ___XX_XX,_XX_XX__,_____XXX,X_XX__X_,
  XXXX_XXX,__X__XX_,X_XXX_XX,XXXXXXXX,
  __XX_XXX,X__X___X,_XXXXXX_,X_X__X_X,
  __X_X_X_,_X__XX__,_XX_X___,XXX_XX_X,
  X__XXX__,_X___X_X,X_X__X__,__X___X_,
  XXXXX___,__XX__XX,__X_X_X_,XXX_X__X,
  X_XX_XXX,__XXXXX_,_X__XX_X,__XX__XX,
  _XX_XX__,_X_XX__X,XX_X__XX,__X_____,
  XX_XX_X_,X__XXX_X,___X_X_X,XXX____X,
  ___X_XXX,_X____XX,XX______,________,
  _XXX____,XX__XX__,X__XX_XX,_XXXX__X,
  __XX___X,XX_XX_X_,XXXXXXXX,XX_X___X,
  __X_XX_X,XXX_____,X_X_XXX_,__XXXX_X,
  _XXXXX__,XX___XXX,_XX___XX,_XXXXX_X,
  X_XXX___,__XX__X_,XXX___X_,X__X_XXX,
  _X_X___X,XX_XX___,_XX_____,____X___,
  _XX___X_,___XXX__,_X_XXXXX,_X_XX_X_};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontCNFont_CharInfo[9] = {
   {  32,  32,  1, acGUI_FontCNFont_4ECB } /* code 4ECB */
  ,{  32,  32,  1, acGUI_FontCNFont_5165 } /* code 5165 */
  ,{  32,  32,  1, acGUI_FontCNFont_529B } /* code 529B */
  ,{  32,  32,  1, acGUI_FontCNFont_5F0F } /* code 5F0F */
  ,{  32,  32,  1, acGUI_FontCNFont_5FC3 } /* code 5FC3 */
  ,{  32,  32,  1, acGUI_FontCNFont_6CF5 } /* code 6CF5 */
  ,{  32,  32,  1, acGUI_FontCNFont_78C1 } /* code 78C1 */
  ,{  32,  32,  1, acGUI_FontCNFont_79BB } /* code 79BB */
  ,{  32,  32,  1, acGUI_FontCNFont_8840 } /* code 8840 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontCNFont_Prop9 = {
   0x8840 /* first character */
  ,0x8840 /* last character  */
  ,&GUI_FontCNFont_CharInfo[  8] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontCNFont_Prop8 = {
   0x79BB /* first character */
  ,0x79BB /* last character  */
  ,&GUI_FontCNFont_CharInfo[  7] /* address of first character */
  ,&GUI_FontCNFont_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontCNFont_Prop7 = {
   0x78C1 /* first character */
  ,0x78C1 /* last character  */
  ,&GUI_FontCNFont_CharInfo[  6] /* address of first character */
  ,&GUI_FontCNFont_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontCNFont_Prop6 = {
   0x6CF5 /* first character */
  ,0x6CF5 /* last character  */
  ,&GUI_FontCNFont_CharInfo[  5] /* address of first character */
  ,&GUI_FontCNFont_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontCNFont_Prop5 = {
   0x5FC3 /* first character */
  ,0x5FC3 /* last character  */
  ,&GUI_FontCNFont_CharInfo[  4] /* address of first character */
  ,&GUI_FontCNFont_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontCNFont_Prop4 = {
   0x5F0F /* first character */
  ,0x5F0F /* last character  */
  ,&GUI_FontCNFont_CharInfo[  3] /* address of first character */
  ,&GUI_FontCNFont_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontCNFont_Prop3 = {
   0x529B /* first character */
  ,0x529B /* last character  */
  ,&GUI_FontCNFont_CharInfo[  2] /* address of first character */
  ,&GUI_FontCNFont_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontCNFont_Prop2 = {
   0x5165 /* first character */
  ,0x5165 /* last character  */
  ,&GUI_FontCNFont_CharInfo[  1] /* address of first character */
  ,&GUI_FontCNFont_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontCNFont_Prop1 = {
   0x4ECB /* first character */
  ,0x4ECB /* last character  */
  ,&GUI_FontCNFont_CharInfo[  0] /* address of first character */
  ,&GUI_FontCNFont_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontCNFont = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,33 /* height of font  */
  ,33 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontCNFont_Prop1}
  ,28 /* Baseline */
  ,15 /* Height of lowercase characters */
  ,22 /* Height of capital characters */
};

