/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font Converter (Demoversion) for emWin version 5.26         *
*        Compiled Aug  8 2014, 14:06:18                              *
*                                                                    *
*        (c) 1998 - 2014 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: CNFont.c                                              *
* Font:        ºÚÌå                                                  *
* Height:      33                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  33                                           *
* Range disabled:       0000 - FFFF                                  *
* Range enabled:        4ECB - 4ECB                                  *
* Range enabled:        4ECB - 4ECB                                  *
* Range enabled:        4ECB - 4ECB                                  *
* Range disabled:       0000 - FFFF                                  *
* Range enabled:        4ECB - 4ECB                                  *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: D:\[3]R&D and QA\emWin\EmWin\Icon\jin.c         *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: D:\[3]R&D and QA\emWin\EmWin\Icon\CNFont-Unicode.txt*
* Character enabled:   0x4ED9 (20185)                                *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontCNFont;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontCNFont_4ECB[132] = { /* code 4ECB */
  X__X___X,__XXXXXX,X___XX__,X__X_X__,
  XXX__XX_,_XX___X_,__X_XXX_,_X_XX__X,
  __X_XX__,_X_X__X_,_XX_XX__,X_XXX_X_,
  _X___XXX,__XX___X,XXX__X_X,XXX__XX_,
  X__XXXX_,X_XXXXX_,___XXXXX,X_XXX_X_,
  XX__XXX_,_X__XX__,___X_XXX,XXXX_XXX,
  _X__X_X_,_X_X_XX_,XXXX_XX_,X_XX__XX,
  _X__X_XX,XXX_XXXX,X__XX_XX,_____X_X,
  _XXXX_XX,XX__XX__,_XX____X,_X_X__XX,
  X_X_X__X,_X__XX__,___X___X,XXXXXX_X,
  __XXXX__,_X_X_X__,XX_X_XX_,X__XX_X_,
  XXXXXXXX,XXX____X,X_XX_X_X,X__XXX_X,
  _XXXX___,XX__X_XX,_XXX__XX,XX___XX_,
  ____X__X,_X____XX,__X___X_,_X_XX_XX,
  _X_XXXX_,_X_X_X__,X__X_X_X,XX_X_XXX,
  X_X_X_XX,_XXXXXXX,X__X___X,XX_XXXX_,
  X__XX_XX,X_XX___X,__XXXX_X,_____XXX,
  __XXXXX_,___X__X_,XXX__X__,_XXXX__X,
  ______XX,XX_XXXXX,XX_X___X,X_X____X,
  X__XXXX_,XX______,X_XXXXXX,XX____X_,
  X_XXX__X,__XX_X__,X_XXX_X_,_____X_X,
  ___X_XXX,__X_XX_X,X__XX__X,_X_XXXXX,
  _______X,X___X_X_,_____XX_,XXXXXX__,
  X__X__XX,___XXXX_,XXXXX_XX,X___XX_X,
  _X__XX_X,XX______,_X_X_X_X,XX__XX__,
  _X__X___,__XXXXXX,_X_XXX_X,___X___X,
  ___XX_X_,_XXXXX_X,_XX___XX,X_X_X__X,
  __X__XX_,___X__XX,_XXXX_XX,_X_X___X,
  _X_XXXXX,_X___X__,XX___X__,X__X___X,
  XX_X__X_,X_XX_X_X,_XX_XX__,XXXXXXXX,
  __XXX___,____X_X_,X__X____,XXX__X__,
  _X_XX_X_,X___XXXX,X_X_X_X_,__XX__X_,
  X_X_XXXX,__X_XXX_,XXXXX___,_XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFont_4ED9[132] = { /* code 4ED9 */
  X____X_X,_XXX_X_X,X_XXX_XX,X_XX_X_X,
  _____X_X,_XXX___X,XXXX__X_,XX_X__X_,
  __X__XX_,X_X___X_,__XX___X,____X_X_,
  X_XX_XXX,__X_X__X,XX______,_X__XXX_,
  XX___X_X,XX_XX_X_,XX______,_X_XX_XX,
  __X__X_X,_______X,__XX___X,XX__XXXX,
  _XX_X___,_XXXXX__,X_X_____,_XX_X__X,
  _X__X_XX,_X_XX_XX,X_XXXX__,X_XXXXXX,
  X__X__XX,_X__X_XX,____XXX_,X_XX___X,
  __XXXX__,XXX___XX,X__X___X,XXXX_XX_,
  XX_XXXXX,_XX___X_,__XXX_XX,XXXX_X_X,
  _X_X___X,XX_XX___,__X_XX_X,X___X_X_,
  ____X_XX,XXXX_X__,X_XX_XXX,___X_XXX,
  __XXXXX_,X____XXX,__X_X_X_,X_XXXXXX,
  XX_____X,XXXXX___,_XX__X__,__XX__X_,
  X___X__X,__X___X_,XX___X__,_XX_X_XX,
  _X_XXX__,X____X_X,__XX___X,___X___X,
  __X____X,_XX_XX__,_____XXX,_X_XXX_X,
  XXXX_XXX,XX_X__XX,_XX_X_XX,X_X_XXX_,
  X__X__XX,X_X_XXXX,_XX__X_X,_XXXXX_X,
  _XXXXX__,X_X_X_X_,______X_,X_X__XXX,
  ______XX,____XX_X,X__XX___,X__X_X__,
  X_XXXX_X,__X_X__X,__X_XXX_,XX__XX_X,
  _XX__XX_,XX_X_XXX,X___X__X,XXXX_X__,
  _X__X_XX,X_X_X___,XX______,_XXX_X_X,
  __XXXXX_,_XX__XX_,X__X_X__,_XX__X_X,
  ___X_XX_,________,XXX_____,XXX_XX_X,
  XXXX__XX,XX_X_XXX,___XX__X,XXXXX__X,
  XXX___X_,X____XX_,X_XXX__X,X_____XX,
  ___X__X_,___XX__X,____XXXX,X_X_X___,
  ___XXX_X,X__XX___,__X__X__,XX__XXX_,
  _____XX_,X_X_XX_X,_XX__XXX,__XX____,
  ____XX_X,XXXX_XX_,_X_XXX_X,XX_XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFont_5165[132] = { /* code 5165 */
  _X__XXXX,XXX__XX_,__XX_XXX,__X_XXX_,
  X_X_XX__,__X____X,X_X__X__,_X_X__X_,
  ___X_X_X,__X___X_,_XXX_X__,__X___X_,
  X_X__X_X,XX__X__X,_XX_XX__,_____XXX,
  ____XX_X,X__X__X_,_XX_XX_X,X_X_X_XX,
  _XX__X__,XX_XX_X_,_XXX_X__,___X_X_X,
  X_______,XX_XX___,__XXX_XX,XX____XX,
  XXXX__X_,XX_XX___,XXXXX_X_,_X_XX___,
  _X_X__X_,_XX_X___,__X____X,___XXXX_,
  X_X__X__,XXXXX__X,XXX_XXX_,____X__X,
  X__X_XXX,_X_XXXXX,X_XXXX__,XXXX_XX_,
  __XX__X_,_XXX_XXX,XX_____X,_XX__XXX,
  __X__X__,___X_X__,XXXXXXX_,XX____XX,
  XXX_XX__,_XX_X_XX,X_XXXXX_,_XX_X_X_,
  _XX_____,__XX___X,_X_X__X_,____XXXX,
  XXXX_X__,X_XX_XX_,____XXXX,_XXXXX__,
  _X_XX___,_XX_X_XX,X__X__X_,__XX_X_X,
  _X_X_X_X,_XX_X___,XX___X__,XX_X__X_,
  _XXXX_XX,__XXXX__,XX_____X,__XX___X,
  _XXXXX__,__XXX__X,XXXX_XX_,XX__X_XX,
  __XXX_X_,___XXXX_,_X__X__X,XXXXX__X,
  XX_XXX__,X_XXX_X_,X_XXX__X,__XX___X,
  X____XX_,_X___X__,XXXXXXX_,X__XX___,
  __X____X,X_X_X_XX,__XX__X_,XX_XX_X_,
  _XX__X_X,XXXX_X_X,____X__X,_X__X__X,
  _XXXXX_X,X___XXXX,X__X_X__,X_X_XX_X,
  X__XX___,XX_____X,XX__XXXX,X____X__,
  X___X__X,___X_X_X,____X_X_,_X__XXXX,
  X_X___XX,X_XXXXX_,XX__X_XX,_X_X____,
  __XX_X_X,___XX_XX,XXXX___X,XXX___X_,
  _X___X__,__XXX_X_,X_X___XX,_X_XXX__,
  __XXXXX_,_X___X_X,X_______,X__X__X_,
  _XXXXXX_,_XXX_X_X,_XX_XXXX,_XX_X_X_};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFont_529B[132] = { /* code 529B */
  X____X__,___XXXX_,_X_XXXX_,__XXXXX_,
  _X__XX__,X_XX___X,__X___XX,XX__X_X_,
  X___XXXX,_X__X_X_,X_XXX__X,_XX_XXXX,
  XX_XXXX_,__XX___X,XX_XX_X_,_XX___X_,
  ___XXXXX,XX__X__X,XXXXX_XX,XX_XXX_X,
  X_X__X__,XX__X_XX,XX__X_XX,____X_XX,
  XXXXX___,_X__X_XX,_XXXXX_X,__X__XX_,
  _XX___XX,_XXXX_XX,XXXXXXX_,_X____X_,
  X_X__X__,XXX_XXX_,_X_XX___,_XX__X_X,
  X_X_XXX_,XXX_XX__,_XXXX_X_,___XXXXX,
  XX_X____,_XX_XX__,____XX__,X___X_XX,
  XX_____X,__X___XX,_XX_X__X,__X_XXXX,
  XXX_XXX_,___XX___,X_X_X_XX,_____XX_,
  _X__X_X_,X__X_XX_,X____XXX,XX_X_XXX,
  X___XXXX,__XXXX__,XX_XX_X_,X_____X_,
  _X_XX_X_,XXXXX__X,_X__XX__,_X_XX__X,
  ___XXX__,_XX_XXXX,___X___X,___XX_X_,
  _X__X___,___XX_XX,___X_XX_,X__XXX_X,
  _X_X_XXX,_X____X_,XXX____X,X_X__XXX,
  XX_X____,X_X_XX_X,XXX_XXXX,___X_X_X,
  _XX__XX_,__XXX__X,_XX__X_X,_X_XXX_X,
  X_X_X___,XXX__XXX,_XX___X_,_XXX_X__,
  ________,__XX____,XXX_XXXX,X_____X_,
  _X__XX_X,_XXX__X_,XX__XXXX,__XX___X,
  _X_X_X_X,___XXX__,_X_XX_XX,XX_____X,
  X___X___,_XXX__X_,_XXX__X_,_X______,
  _______X,X__XXXX_,XX_X_XX_,__X__XXX,
  XXX_XX_X,X_X__X_X,X__XXX__,__XX_X__,
  _X_X_XX_,XXX_X___,_XX__XXX,______X_,
  _XX_XX_X,_______X,__XXXX__,X_X_____,
  _X_X_XX_,_X_XX_X_,___X__X_,_XX__XX_,
  _X_X_X__,_XX__XX_,XX_XX___,______X_,
  XXX__XXX,X___XX_X,_X__X_XX,XX_X__X_};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFont_5F0F[132] = { /* code 5F0F */
  _XX_XXX_,_____XX_,X_XXX_XX,X__X_XX_,
  XX_XXXX_,X_XX_X_X,_XX_X_XX,X_____XX,
  XXXX_XX_,__X___X_,_____XXX,_X_XXXX_,
  X_XXXXXX,_X_XX_X_,__X_XXXX,X_XX___X,
  X___XXXX,_XXXXX__,_X_X_X__,_XX_XXXX,
  XX_X___X,_X___X__,X_X____X,_X__X_X_,
  __X_X__X,XXX_XX__,_XX_X_X_,X_X_XXX_,
  XX__XXXX,_XXXXX_X,X____X_X,____XX_X,
  X____X__,XXXXXXXX,XX___XXX,_XXX__XX,
  XXXXX__X,XXXXX_XX,X__XX_X_,X_X__XXX,
  XXX_X_XX,X_X_X___,X_XX___X,_XX__XXX,
  X____XXX,X__XXXXX,_X___X__,XXX_X_X_,
  _XX_X_XX,____XX_X,XX_XX__X,XXXXX_XX,
  X___XXXX,__X_X_XX,_X_XXX__,XX__X_X_,
  __XX__X_,_XX_X_X_,XXX_X__X,X__X_X_X,
  __X___X_,XXXXXX__,XX___XXX,_XXX_XXX,
  _____X__,X___X___,XX__X_XX,XXX__X_X,
  __X_XXXX,XX___X_X,__X_XX_X,_XX__XXX,
  XX_X__XX,X_X_X_X_,__XX__X_,_XX_XX_X,
  _XX__XX_,__X_XXX_,_X_X_XX_,__XX_X__,
  XXX_X__X,XXXX____,X_X__X_X,__XXXX__,
  _X__X_X_,X____X_X,XXXXX___,_XX_XXX_,
  __X_XXX_,_XX___XX,X__XXXX_,XX_XXX_X,
  ___X__X_,__X_XXXX,XX__XXXX,__X_XX__,
  XXX___X_,XXXX___X,__X___X_,__X_X___,
  _XX___X_,X___X__X,_X_____X,_X_XX_XX,
  XX__XX__,__XX_XX_,__X_____,_X_XX___,
  _X_XXX__,XXXXXXXX,X__XX_X_,_X__XXXX,
  ____XXXX,X_____XX,XX__XX_X,XX__X___,
  _XXXXX_X,XX__X__X,XX__XXXX,____X_X_,
  __XX___X,XX_____X,____XX__,XXXXXXX_,
  XX_XX_XX,X__XXXXX,X____X_X,XXXX__XX,
  _______X,_____X_X,_XXXXX__,XXXXX_X_};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFont_5FC3[132] = { /* code 5FC3 */
  XXXX____,X_X__XX_,XXXX_XX_,XXXXXXXX,
  XX_X_X_X,X_XX_X_X,X__X_X_X,__XX__X_,
  XX_X_X__,XX_XXX_X,XX_XX___,XX__XX__,
  XXX__XXX,XXX_XXXX,X_______,___X__XX,
  __XX_XXX,XXXX_XXX,__XX__X_,X_X___X_,
  ________,_X__XXXX,X_XX_X_X,XX___XX_,
  _XX___XX,XX_XXXX_,___X_XXX,XX_X____,
  XX___X_X,__X_X___,___X___X,__XXXXXX,
  X_XX_XXX,_XX_X___,_X__XXXX,_XXXXXXX,
  X_____X_,X_XXX_XX,___X_XX_,____X_XX,
  X_XX_X_X,____XX__,XX_X____,X__X__XX,
  __XX___X,_X_XXXX_,_XXXXX__,X__X_XXX,
  XXX_____,X_XXX___,X______X,X_X__XX_,
  ___XXX_X,_X_XXX_X,__XX_XX_,X_X_XX_X,
  _X____XX,_XX_XXXX,_X_XX_X_,____X_XX,
  __X__XXX,_X_XX_XX,_XXXXX_X,X______X,
  ____X___,_X_X_XX_,X_XXX_X_,___XX_XX,
  X_XXX_XX,__XXX__X,_XX__X__,X_X____X,
  ____XX_X,X__XXX_X,X__XX_X_,XXX_X___,
  XX_X__XX,__X___XX,__XX_X_X,_X______,
  XXXX_XX_,X__X_XX_,___XXX__,______X_,
  _____XX_,XX_X____,__X_____,X__XX__X,
  X_XXX_X_,X_XXX___,___XX___,_X_X_X__,
  XX__X_XX,X_X__XX_,X_X__X_X,_X_X_X__,
  _X__XXX_,__XXX_X_,__X_XX_X,X_XX_XXX,
  X_X__XX_,X_XX___X,XXXX_XXX,X_______,
  _XX__X__,_XXXXX__,_X__X___,__XX__XX,
  __XX_XXX,_X_X_X__,_X_XX_XX,_____X__,
  __XXX__X,XX__X_X_,XXXXX__X,X_X___X_,
  __XXX_XX,_X_XX_X_,X__X__XX,X__X__X_,
  X__X____,___XX___,___X____,__X_XXXX,
  __X_X__X,XX_X_XX_,X___X___,___X__X_,
  X__XX__X,__XX_X_X,________,X_XX_XXX};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFont_6CF5[132] = { /* code 6CF5 */
  X_XXX__X,X_X__XXX,_X_X____,XX_XX_X_,
  XX_X_X__,XXX_XXX_,_X___X__,_XX_XX__,
  XXXX_X__,X_X_XX__,XX_XXXXX,XXXXX_XX,
  ____XXX_,_XX__X__,XX__XXX_,XXX__XX_,
  X_X___X_,_X_XXX__,___X___X,X_X_X_X_,
  _XX____X,XX__X__X,_XXXX_X_,X_XXXX__,
  XXX_XXXX,X_X___XX,XX__XX__,X____XXX,
  X__X_XXX,_X__X_XX,XXXX_X_X,___X__XX,
  X_______,__X_XX__,XX____X_,XXXX_XXX,
  XX_XXX__,___XXXXX,_____XXX,XX_XXXXX,
  ___X_X__,XX_XX__X,X_X___X_,_XXXXXXX,
  XX__X___,_XX_X_XX,_XXX__X_,_X_XX_X_,
  X_XXXX_X,XX_X_XX_,_XX__XX_,XX_____X,
  _XX_X__X,__XXX___,X_X_X___,XXX___XX,
  ____XXXX,_X_XXX__,__X__X__,_X__XX_X,
  _X____X_,_X___X_X,_X__XXXX,_XXX_XXX,
  X__XXX_X,X_X_X_X_,XX_XX__X,XX___X_X,
  __X__X_X,X__XXXX_,_X__XXXX,X____X__,
  XXXXX_X_,X_XX____,XX__X_X_,X_X_XX__,
  X__X_X_X,___X_X_X,X_____XX,_XXXX_X_,
  XX___X__,_X_X_XXX,XXXX_X_X,XXX____X,
  XX__X__X,__XXX_XX,X_X__X__,___XX___,
  XXX_X__X,__XXXX_X,_XXXX__X,X_XXX___,
  _XXX_X_X,__X_X___,XXXXX_X_,XX_X_XXX,
  X___XXXX,X_X___X_,_XX_XXX_,X_X_XX__,
  X____XXX,XXX__XXX,_X___X_X,XX_XX_XX,
  _XXXX___,_X___XXX,X____XX_,_XXX____,
  ___X__XX,__XXXX_X,__XXXX__,XXXXXXX_,
  XX_X__X_,____X__X,_X_X_XXX,_X_XX_X_,
  X_XX____,XXX_X_XX,XXX__XX_,_X____XX,
  _XX_X_XX,_X_____X,___X_XXX,_XXXXXX_,
  __XXX_XX,X_XX__X_,____XX_X,_X_XX_XX,
  X_XX__X_,_____X__,XXX_XX__,X__X_XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFont_78C1[132] = { /* code 78C1 */
  XXXXXXXX,_XXX_X_X,X__X_XXX,__X_____,
  X__XXX__,__XXXXXX,_XXXX_XX,X_XX_XXX,
  _X__XX__,_XXX__XX,___XX__X,X__XX_X_,
  XX__X_XX,X___X_XX,XX___XX_,_X_X_XX_,
  ___XX___,_X_XX_X_,X_X_XX_X,XX_XXX__,
  X___XXX_,X_XX____,_X_XX_XX,XXX_X_XX,
  XXX_XX__,XX_XXX__,__X_____,_XXXXXXX,
  X_XXX__X,X___XXXX,X__XXX_X,X__XXXXX,
  _X_X__X_,X__X____,X__XX_XX,__XX__XX,
  _XXXXXX_,_X__X_X_,__XX__XX,______XX,
  XX__X_XX,_X__XX__,XXX_XXX_,__XX__X_,
  XXX__XX_,_____X_X,XX_X___X,__X__X_X,
  _XX_X__X,X__XX_XX,X_X__X_X,X___XXXX,
  _XX__X__,XXX_XXXX,X_X___X_,__XX_X_X,
  XXX___XX,XX_X__X_,X__X_X_X,XX_XXXXX,
  X_X__X__,X__XXX_X,____XXXX,X_XXXX_X,
  _XX___X_,_______X,XX_XX__X,XXX_XX__,
  X_XXX___,X__X_XXX,_X_XXXXX,XX___X__,
  X_XXXX_X,X_____X_,_X_X__XX,X_XX_XX_,
  XXXXX__X,_____X__,_XX_X_XX,____XX_X,
  XXX____X,__X_X___,_XXX_XXX,XXXX_X__,
  X_X__X__,X__XXXX_,X___XXX_,XXXX____,
  __XX_X_X,X_X_XXXX,_XX_XXX_,X__XX_XX,
  XX_XXX_X,___X___X,X_X_X___,XX______,
  X_X_X_XX,XX_X___X,X__X__XX,X_XX_XXX,
  _X_XX___,XXX__X__,XX______,___XX__X,
  _XX___X_,X_X_XXX_,XXX___X_,X__X__X_,
  XXX_____,X___XXX_,X_X_X___,__XX_XXX,
  XX_XX_XX,XXXXX___,__XXX_XX,__X_X_XX,
  _X_X__X_,_XXX__XX,XX____XX,______X_,
  __XX__X_,X______X,XX_XX_XX,__XX_XXX,
  XX____X_,X__X__XX,__XXX_XX,XXX_X_X_,
  X_____XX,_XXX____,__XXX_X_,XX__XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFont_79BB[132] = { /* code 79BB */
  X_XXXXXX,X_______,X_X_XX__,X__XX_XX,
  _XX__X_X,XXXX____,___XXX_X,_XXX__X_,
  XX_XXX_X,___XX___,X__XXXXX,___XXXX_,
  __XXX_X_,XX_XX__X,__XXX__X,_XXX____,
  X_XX____,_____X_X,__XXX_XX,X___XXXX,
  XX__XX__,XX__XXXX,X_X_XXXX,X____XXX,
  XX_XX_XX,X__XXX__,__X_X__X,_X_XX_XX,
  __XX__XX,__X___XX,_XX_X___,_X_X__XX,
  _X_X_XXX,_XXXX__X,XX___X_X,_X__XXX_,
  X_XX__XX,XX_XXXXX,__X_X__X,_X_X_XX_,
  XX__XXX_,___X__X_,____XX_X,_XXXXX__,
  ______X_,____X___,_XXX__XX,XX_X__XX,
  _XXX_X__,XXXXXX__,_XXX_XXX,_X_XX__X,
  X___X__X,_XXX___X,________,X_____XX,
  XXX_XXX_,___X_XX_,X___XXX_,_X_X___X,
  _X_XX_X_,X__X__X_,__X__X__,___X____,
  X__X___X,____XX__,X___X__X,__XXX_X_,
  X_XXXXX_,X__X___X,XX__XXX_,XX_XX_X_,
  XX_X__XX,X__X_XX_,X_X_XXX_,_XX___XX,
  XXX_X_X_,X__XX_XX,XXXXX_XX,X___XX__,
  X__X_XX_,X___X__X,___X__X_,___XXX__,
  ___XXXX_,__XXXX__,X_XX_X_X,_XX__XXX,
  XXXX_X_X,X__X_XX_,_X_XXX_X,__X_X___,
  XXX_____,_X____X_,__X__XX_,XXX_X_XX,
  XXXX__XX,XXXX__XX,_XXXXX_X,XXXX_X_X,
  XX__X___,X_X_XX_X,_XXX_XXX,_XXXX_X_,
  X_X_X_X_,___XXX_X,__XXX___,_X__X_XX,
  _X__X_XX,_XXXXXXX,X_X_X___,XX_X_XXX,
  XXXXX___,XXXX____,_X_XXX__,XX__X_X_,
  _X______,___X__X_,_X__XXX_,_X___XXX,
  XXX_X__X,X___X___,_XX__XXX,______X_,
  X_X____X,XXX___XX,_XX_XX__,X_XX_X__,
  _X_X__XX,X_____XX,__XX_X__,_XX____X};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFont_8840[132] = { /* code 8840 */
  ____XXXX,_X____X_,XX____X_,_X_XXXX_,
  X_XX_X__,__XXX_XX,____X__X,__XX____,
  _X_X__XX,XXX_XXX_,XXX__X__,__X_XX__,
  _XXXX__X,_____XX_,X_X__X__,_X_X_XXX,
  XX___XXX,_X__XX__,XXXXX_XX,XX__X_XX,
  XX_X_XX_,____X_XX,XXXX_XX_,__X__XXX,
  ___XX__X,__XX____,X_X__X__,XXX_XXXX,
  X__X_X_X,XXXXXXX_,_X_XX___,X_X__XX_,
  ___X____,_X__XX__,X__XXX_X,X__XX_X_,
  X_X_XX_X,X_XX___X,X___X_X_,___X____,
  X_XXX_X_,___XXXXX,XXX__XX_,__XX__XX,
  X__XXXXX,_XX_X_XX,X___X__X,X_XX_X_X,
  X_XX___X,_XX___X_,XXX_XXX_,_XX_XXXX,
  XX__XXXX,X____X_X,_X_X___X,___XXX_X,
  __XXX__X,XX_____X,X_XX_XX_,_X_XXX__,
  _XXX_XXX,___XXXXX,XX___X__,_XXXXXX_,
  XX_X_XX_,__XX__X_,__X_X___,X_XX_XX_,
  X__X__X_,__X____X,_X_XX___,X_X_X_XX,
  X___X___,X__XXX__,X_X_XX__,XXX_____,
  _XXXXXXX,___XX_X_,XX___X_X,_XX_____,
  _XXXXXX_,_X__XXXX,_______X,____XXXX,
  _X_X__X_,X____X_X,XX____XX,_X_X_X__,
  XX______,XX_____X,XXXXX__X,______XX,
  X__XX_XX,_XX_____,X_X_XX_X,X_X_X__X,
  XX_____X,__XXX_X_,X___XX_X,_____XX_,
  X___X_XX,__X_XXX_,_XX_XXXX,X_X___XX,
  _XX_____,XXX_XX__,_X___X__,X__XX_XX,
  X_XXX__X,XXX__XXX,__XXXX_X,XXX_XXX_,
  _XX_X__X,X__X_X_X,X_XX_X__,X___X_XX,
  _______X,____X_XX,XXXX____,_XX_XXX_,
  XXX_X___,___X____,X_XXX__X,XX_XX___,
  _X_XX__X,___X___X,XXX___XX,____XX_X,
  ___XXXXX,_X_X_X_X,_XXX_XXX,X_____X_};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontCNFont_CharInfo[10] = {
   {  32,  32,  1, acGUI_FontCNFont_4ECB } /* code 4ECB */
  ,{  32,  32,  1, acGUI_FontCNFont_4ED9 } /* code 4ED9 */
  ,{  32,  32,  1, acGUI_FontCNFont_5165 } /* code 5165 */
  ,{  32,  32,  1, acGUI_FontCNFont_529B } /* code 529B */
  ,{  32,  32,  1, acGUI_FontCNFont_5F0F } /* code 5F0F */
  ,{  32,  32,  1, acGUI_FontCNFont_5FC3 } /* code 5FC3 */
  ,{  32,  32,  1, acGUI_FontCNFont_6CF5 } /* code 6CF5 */
  ,{  32,  32,  1, acGUI_FontCNFont_78C1 } /* code 78C1 */
  ,{  32,  32,  1, acGUI_FontCNFont_79BB } /* code 79BB */
  ,{  32,  32,  1, acGUI_FontCNFont_8840 } /* code 8840 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontCNFont_Prop10 = {
   0x8840 /* first character */
  ,0x8840 /* last character  */
  ,&GUI_FontCNFont_CharInfo[  9] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontCNFont_Prop9 = {
   0x79BB /* first character */
  ,0x79BB /* last character  */
  ,&GUI_FontCNFont_CharInfo[  8] /* address of first character */
  ,&GUI_FontCNFont_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontCNFont_Prop8 = {
   0x78C1 /* first character */
  ,0x78C1 /* last character  */
  ,&GUI_FontCNFont_CharInfo[  7] /* address of first character */
  ,&GUI_FontCNFont_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontCNFont_Prop7 = {
   0x6CF5 /* first character */
  ,0x6CF5 /* last character  */
  ,&GUI_FontCNFont_CharInfo[  6] /* address of first character */
  ,&GUI_FontCNFont_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontCNFont_Prop6 = {
   0x5FC3 /* first character */
  ,0x5FC3 /* last character  */
  ,&GUI_FontCNFont_CharInfo[  5] /* address of first character */
  ,&GUI_FontCNFont_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontCNFont_Prop5 = {
   0x5F0F /* first character */
  ,0x5F0F /* last character  */
  ,&GUI_FontCNFont_CharInfo[  4] /* address of first character */
  ,&GUI_FontCNFont_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontCNFont_Prop4 = {
   0x529B /* first character */
  ,0x529B /* last character  */
  ,&GUI_FontCNFont_CharInfo[  3] /* address of first character */
  ,&GUI_FontCNFont_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontCNFont_Prop3 = {
   0x5165 /* first character */
  ,0x5165 /* last character  */
  ,&GUI_FontCNFont_CharInfo[  2] /* address of first character */
  ,&GUI_FontCNFont_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontCNFont_Prop2 = {
   0x4ED9 /* first character */
  ,0x4ED9 /* last character  */
  ,&GUI_FontCNFont_CharInfo[  1] /* address of first character */
  ,&GUI_FontCNFont_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontCNFont_Prop1 = {
   0x4ECB /* first character */
  ,0x4ECB /* last character  */
  ,&GUI_FontCNFont_CharInfo[  0] /* address of first character */
  ,&GUI_FontCNFont_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontCNFont = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,33 /* height of font  */
  ,33 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontCNFont_Prop1}
  ,28 /* Baseline */
  ,15 /* Height of lowercase characters */
  ,22 /* Height of capital characters */
};

